### ISSUE TITLE
[solo] end of the game crashes

### ISSUE THREAD

**Issue by bastienbarthet** [bastienbarthet/schotten-totten#45]
in solo mode, end of the game shall not call endOfTheTurn();
do it only with online mode

**Comment by rvlander** [comment]
Cela correspond-t-il à cette erreur?

```java
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.remove(ArrayList.java:492)
	at com.boardgames.bastien.schotten_totten.model.Hand.playCard(Hand.java:42)
	at com.boardgames.bastien.schotten_totten.ai.GameAI.reclaimAndPlay(GameAI.java:38)
	at com.boardgames.bastien.schotten_totten.ai.MatchRunner.makeTurn(MatchRunner.java:37)
	at com.boardgames.bastien.schotten_totten.ai.MatchRunner.main(MatchRunner.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

**Comment by bastienbarthet** [comment]
si cela se produit a la fin du jeu, peut etre

**Comment by bastienbarthet** [comment]
bug corrigé, seul le jeu en ligne apelle endOfTheTurn() a la fin du jeu
